config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :home, only: [:index] do
    collection do
      get 'about'
    end
  end
  resources :books 
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 200 }
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'successfully'
    else
      # redirect_to books_path
      @user = User.find(@book.user_id)
      render 'users/show'
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    if @book.user_id != current_user.id
      redirect_to books_path
    end

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'successfully'
    else
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])

    if @user != current_user
      redirect_to user_path(current_user.id)
      return
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'successfully'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_flash_class(key)
    if key == "notice"
      return 'alert-info'
    elsif key == "alert"
      return 'alert-danger'
    else
      return ""
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
<h1>Editing Book</h1>

<%= form_for(@book, url: book_path, method: :put) do |f| %>
<% if @book.errors.any? %>
<div id="error_explanation">
  <h2><%= @book.errors.count %>件のerrorが発生しました。</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="form-group has-icon">
      <label >Title</label>
      <%= f.text_field :title, class:"form-control", placeholder:"title" %>
      <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <label >body</label>
    <%= f.text_area :body, class:"form-control", rows:"3", placeholder:"body" %>
  </div>
</div>
<hr>
<%= f.submit "Update Book", class:"btn btn-primary col-xs-12" %>
<% end %>

</div>
</form>

<a class="Show" href=<%= book_path(@book.id) %>>Show</a>
<a class="Back" href="/books">Back</a>

</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">
<%= render 'users/user_info' %>

<div class="col-xs-9">
  <h2>Book</h2>
  <table class="table">
    <thead>
      <th></th>
      <th>Title</th>
      <th>body</th>
    </thead>
    <tbody>

      <% if @books.present? %>
      <% @books.each do |book| %>

      <tr>
	
        <td><a href=<%= user_path(book.user_id) %>>
	    <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></a>
	</td>
        <td><a href=<%= book_path(book.id) %>><%= book.title %></a></td>
        <td><%= book.body %></td>
	<% end %>
	<% end %>
      </tr>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
<%= render 'users/user_info' %>

<div class="col-xs-9">
  <h2>Book detail</h2>
  <table class="table">
    <thead>
      <th></th>
      <th>Title</th>
      <th>body</th>
      <th></th>
      <th></th>

    </thead>
    <tbody>
      <tr>
        <td><a href=<%= user_path(@user.id) %>>
	    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %><%= @user.name %></a>
	</td>
        <td><a href=<%= book_path(@book.id) %>><%= @book.title %></td>
        <td><%= @book.body %></td>
	<td><a class="col-xs-12 btn-sm btn-success" href=<%= edit_book_path(@book.id) %>>Edit</a>
	<td><%= link_to "Destroy", book_path(@book.id), method: :delete, class: "col-xs-12 btn-sm btn-success"%></td>
      </tr>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<% if !user_signed_in? %>
  <a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a>
  <a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a>
<% else %>
  <a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href=<%= user_path(current_user.id) %>>Log in</a>
  <a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href=<%= user_path(current_user.id) %>>Sign Up</a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookers</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head> 

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
	<nav class="nav navbar-nav navbar-left">
	  <span style="color:white;">Bookers</span>
	</nav>
	<nav>
	  <ul class="nav navbar-nav navbar-right">
	    <% if !user_signed_in? %>
            <li><a class="glyphicon glyphicon-home home" href="/"> Home</a></li>
            <li><a class="glyphicon glyphicon-link about" href="/home/about"> About</a></li>
            <li><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a></li>
            <li><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a></li>
	    <% else %>
            <li><a class="glyphicon glyphicon-home home" href=<%= user_path(current_user.id) %>> Home</a></li>
            <li><a class="glyphicon glyphicon-user users" href="/users"> Users</a></li>
            <li><a class="glyphicon glyphicon-book books" href="/books"> Books</a></li>
            <li><a class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>
	    <% end %>
	  </ul>
	</nav>
      </div>
    </header>
    <div class="body">
      <div class="container">
	<% flash.each do |key, value| %>
	<%= content_tag :div, value, class: [:alert, get_flash_class(key)] %>
<p class=<%= "alert #{get_flash_class(key)}" %>>
	<% end %>
	    
	<%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/_user_info.html.erb
<div class="col-xs-3">
  <h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
<table>
  <tbody>
    <tr>
      <th>Name</th>
      <th><%= @user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
  <a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" href=<%= edit_user_path(current_user.id) %>></a>
</div>

<h2>New book</h2>
    
<%= form_for(@book, url: books_path) do |f| %>
<% if @book.errors.any? %>
<div id="error_explanation">
  <h2><%= @book.errors.count %>件のerrorが発生しました。</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="form-group has-icon">
      <label class="control-label sr-only">Title</label>
      <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
      <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= f.text_area :body, class:"form-control", rows:"3", placeholder:"コメント" %>
  </div>
</div>
<hr>
<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
<% end %>

</div>
</form>

app/views/users/edit.html.erb
<h1>User info</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_for(@user, url: user_path, method: :put) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= @user.errors.count %>件のerrorが発生しました。</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="form-group has-icon">
      <label class="control-label sr-only">Name</label>
      <%= f.text_field :name, class:"form-control", placeholder:"name" %>
      <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= f.attachment_field :profile_image %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= f.text_area :introduction, class:"form-control", rows:"3", placeholder:"" %>
  </div>
</div>
<hr>
<%= f.submit "Update User", class:"btn btn-primary col-xs-12" %>
<% end %>

</div>
</form>

</div>

<div class="col-xs-9">

app/views/users/index.html.erb
<div class="container">
<div class="row">
<%= render 'users/user_info' %>

<div class="col-xs-9">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <th>image</th>
      <th>name</th>
      <th></th>
    </thead>
    <tbody>

      <% if @users.present? %>
      <% @users.each do |user| %>

      <tr>
	
        <td><a href="">
	    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></a>
	</td>
        <td><%= user.name %></td>
        <td><a class="btn-sm btn-success" href=<%= user_path(user.id) %>>Show</a></td>
	<% end %>
	<% end %>
      </tr>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">

<%= render 'users/user_info' %>

<div class="col-xs-9">
  <h2>Books</h2>
  <table class="table">
    <thead>
      <th></th>
      <th>Title</th>
      <th>body</th>
    </thead>
    <tbody>
      <% if @books.present? %>
      <% @books.each do |book| %>

      <tr>
	
        <td><a href="">
	    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></a>
	</td>
        <td><a href=<%= book_path(book.id) %>><%= book.title %></a></td>
        <td><%= book.body %></td>
	<% end %>
	<% end %>
      </tr>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>